import os

# Email information
SMTP_FROM_EMAIL = os.getenv('SMTP_FROM_EMAIL')
SMTP_EMAIL_HOST = os.getenv('SMTP_EMAIL_HOST')
SMTP_EMAIL_PORT = os.getenv('SMTP_EMAIL_PORT')
SMTP_EMAIL_HOST_PASSWORD = os.getenv('SMTP_EMAIL_HOST_PASSWORD')
DEFAULT_REPLY_TO_EMAIL = os.getenv('DEFAULT_REPLY_TO_EMAIL')

# Service Bus
SB_CONNECTION_STR = os.getenv('SB_CONNECTION_STR')
EMAIL_QUEUE = os.getenv('EMAIL_QUEUE')
ERROR_EMAIL_QUEUE = os.getenv('ERROR_EMAIL_QUEUE')
SB_MAX_WAIT_TIME = os.getenv('SB_MAX_WAIT_TIME')
SB_MESSAGES_TO_READ = os.getenv('SB_MESSAGES_TO_READ')


# É APENAS PARA TESTE NOS ARQUIVOS "test_sync"
NAMESPACE_CONNECTION_STR = os.getenv('NAMESPACE_CONNECTION_STR')
QUEUE_NAME = os.getenv('QUEUE_NAME')
